export const WORKS = [
  {
    id: "work-1",
    preview: "/assets/works/1/preview.jpg",
    name: "The Rosa",
    type: "Frontend Development",
    liveUrl: "https://elyor2005.github.io/The-Rosa/",
    client: "The Rosa",
    year: 2024,
    description:
      "I developed a visually captivating and interactive website for The Rosa, a stylish brand concept. This modern landing page combines minimalistic elegance with smooth animations to create an immersive user experience. The design is built around a soft, pastel-themed aesthetic, perfectly aligned with high-end fashion or beauty branding. The site utilizes cutting-edge web technologies such as HTML, CSS, JavaScript,  to deliver seamless transitions and scroll-triggered effects. This project demonstrates my ability to craft elegant, responsive, and animation-rich websites with a strong focus on user experience and visual storytelling.",
    images: [
      "/assets/works/1/preview.jpg",
      "/assets/works/1/1.jpg",
      "/assets/works/1/2.jpg",
    ],
  },
  {
    id: "work-2",
    preview: "/assets/works/2/preview.jpg",
    name: "Sea Side",
    type: "Frontend Development",
    liveUrl: "https://elyor2005.github.io/Sea-Side/",
    client: "Sea Side",
    year: "2024",
    description:
      "I created a vibrant and engaging website called Sea Side, designed to showcase a serene ocean-themed landing page with immersive visuals and motion effects. The site captures the calm and beauty of seaside life through creative layout, color palette, and animation. Built using HTML, CSS, JavaScript  the project features smooth scrolling, parallax effects, and animated elements that respond to user interaction. This project highlights my skills in building aesthetic, responsive, and animation-driven web experiences that emphasize both design and functionality",
    images: [
      "/assets/works/2/preview.jpg",
      "/assets/works/2/1.jpg",
      "/assets/works/2/2.jpg",
    ],
  },
  {
    id: "work-3",
    preview: "/assets/works/3/preview.jpg",
    name: "Portfolio",
    type: "Frontend Development",
    liveUrl: "https://elyor2005.github.io/Portfolio-Demo/",
    client: "By Someone",
    year: "2024",
    description:
      "I developed a sleek and modern Portfolio Demo website to present creative work in a clean and structured format. This responsive, single-page design highlights key sections such as About, Skills, Projects, and Contact, offering a smooth user experience. The website is built using HTML, CSS, and JavaScript, with subtle animations and transitions enhancing the visual appeal. The layout is intuitive and mobile-friendly, demonstrating my ability to create professional personal portfolios that effectively showcase individual branding and technical skills.",
    images: [
      "/assets/works/3/preview.jpg",
      "/assets/works/3/1.jpg",
      "/assets/works/3/2.jpg",
    ],
  },
  {
    id: "work-4",
    preview: "/assets/works/4/preview.jpg",
    name: "Discord",
    type: "Frontend Development",
    liveUrl: "https://elyor2005.github.io/Discord-Clone/",
    client: "By Discord",
    year: "2024",
    description:
      "I built a clean and responsive Discord Clone landing page that closely replicates the modern design and layout of the original Discord homepage. This project demonstrates my ability to recreate real-world UI designs with precision and attention to detail. Developed using HTML, CSS, and JavaScript, the site includes structured sections, hover effects, and a polished user interface. The layout adapts smoothly across devices, showcasing my front-end development skills in responsive design, layout structuring, and brand-style replication.",
    images: [
      "/assets/works/4/preview.jpg",
      "/assets/works/4/1.jpg",
      "/assets/works/4/2.jpg",
    ],
  },
  {
    id: "work-5",
    preview: "/assets/works/5/preview.jpg",
    name: "Hulu",
    type: "Frontend Development",
    liveUrl: "https://elyor2005.github.io/Hulu/",
    client: "By Hulu",
    year: "2024",
    description:
      "I developed a visually accurate Hulu Clone landing page inspired by the official Hulu website. The project focuses on recreating the platform`s modern streaming interface with attention to layout, typography, and design consistency. Built using HTML, CSS, and JavaScript, the page features a responsive grid system, vibrant call-to-action elements, and a sleek dark theme that mirrors Hulu`s branding. This project highlights my ability to clone real-world websites with pixel-perfect design and optimized responsiveness for both desktop and mobile devices.",
    images: [
      "/assets/works/5/preview.jpg",
      "/assets/works/5/1.jpg",
      "/assets/works/5/2.jpg",
    ],
  },
  {
    id: "work-6",
    preview: "/assets/works/6/preview.jpg",
    name: "BrainWave",
    type: "Frontend Development",
    liveUrl: "https://brainwavedemoapp.netlify.app/",
    client: "By BrainWave",
    year: "2025",
    description:
      "I developed Brainwave, a cutting-edge AI-powered landing page designed to showcase the capabilities of futuristic technology. The site features a bold, modern UI with dynamic animations and clean layout transitions. Built using React.js, Tailwind CSS, and Framer Motion, the project demonstrates advanced front-end skills in component-based architecture, responsive design, and smooth motion effects. The dark theme combined with vibrant gradients and 3D-inspired visuals delivers a sleek, immersive user experience. This project reflects my ability to create high-quality, modern interfaces optimized for performance and engagement.",
    images: [
      "/assets/works/6/preview.jpg",
      "/assets/works/6/1.jpg",
      "/assets/works/6/2.jpg",
    ],
  },
  {
    id: "work-7",
    preview: "/assets/works/7/preview.jpg",
    name: "Virtual Vision",
    type: "Frontend Development",
    liveUrl: "https://virtualvison.netlify.app/",
    client: "By Virtual Vision",
    year: "2025",
    description:
      "I created Virtual Vision, a futuristic and visually rich landing page for a tech-oriented brand focused on innovation and digital experiences. The design emphasizes modernity through bold typography, gradient backgrounds, and smooth section transitions. Developed using React.js, Tailwind CSS, and Framer Motion, the site showcases advanced animation techniques and responsive design principles. With a clean UI and engaging scroll-based effects, this project demonstrates my expertise in building immersive front-end experiences that align with emerging tech themes and futuristic branding.",
    images: [
      "/assets/works/7/preview.jpg",
      "/assets/works/7/1.jpg",
      "/assets/works/7/2.jpg",
    ],
  },
  {
    id: "work-8",
    preview: "/assets/works/8/preview.jpg",
    name: "Restaurant ",
    type: "Frontend Development",
    liveUrl: "https://elyor2005.github.io/Restaurant/",
    client: "By Restaurant",
    year: "2025",
    description:
      "I built a stylish and responsive Restaurant landing page using React.js, showcasing a clean and modern interface tailored for the food and hospitality industry. The website highlights sections like the menu, specials, and reservation details, all presented with smooth navigation and engaging visuals. Styled with CSS and structured with React components, the design ensures scalability and maintainability. This project demonstrates my ability to develop professional, user-centric web applications using modern React practices with a strong emphasis on visual presentation and user experience.",
    images: [
      "/assets/works/8/preview.jpg",
      "/assets/works/8/1.jpg",
      "/assets/works/8/2.jpg",
    ],
  },
  {
    id: "work-9",
    preview: "/assets/works/9/preview.jpg",
    name: "Redefine ",
    type: "Frontend Development",
    liveUrl: "https://elyor2005.github.io/redefine/",
    client: "By Redefine",
    year: "2025",
    description:
      "I developed Redefine, a sleek and futuristic landing page using React.js and Tailwind CSS, designed to showcase high-end branding with a strong visual identity. The interface combines bold typography, clean grid layouts, and a minimalist aesthetic to deliver a premium look and feel. Enhanced with GSAP for smooth, scroll-triggered animations, the site offers a dynamic and immersive user experience. This project highlights my expertise in building responsive, component-based UIs and integrating modern animation libraries to elevate the visual impact of web applications.",
    images: [
      "/assets/works/9/preview.jpg",
      "/assets/works/9/1.jpg",
      "/assets/works/9/2.jpg",
    ],
  },
  {
    id: "work-10",
    preview: "/assets/works/10/preview.jpg",
    name: "VastuSpaze ",
    type: "Frontend Development",
    liveUrl: "https://elyor2005.github.io/VastuSpaze/",
    client: "By VastuSpaze",
    year: "2025",
    description:
      "I developed VastuSpaze, a clean and elegant landing page tailored for interior design and architecture services. Built with HTML, CSS, and JavaScript, the site features a soft, modern color scheme, professional layout, and smooth scroll behavior to create a refined and welcoming user experience. The design emphasizes clarity and structure, making it ideal for showcasing design philosophy, services, and brand identity. This project highlights my ability to create responsive, visually balanced websites that align with the aesthetics and goals of creative service industries.",
    images: [
      "/assets/works/10/preview.jpg",
      "/assets/works/10/1.jpg",
      "/assets/works/10/2.jpg",
    ],
  },
  {
    id: "work-11",
    preview: "/assets/works/11/preview.jpg",
    name: "Stream Clone ",
    type: "Frontend Development",
    liveUrl: "https://elyor2005.github.io/Stream-clone/",
    client: "By Stream",
    year: "2025",
    description:
      "I built a visually engaging Stream Clone landing page inspired by modern streaming platforms. Designed using HTML, CSS, and JavaScript, the site replicates the sleek layout and bold visuals typical of popular entertainment services. The dark theme, featured content sections, and responsive grid layout provide an immersive user experience across all devices. This project demonstrates my ability to recreate real-world UI designs with attention to branding, responsiveness, and front-end performance.",
    images: [
      "/assets/works/11/preview.jpg",
      "/assets/works/11/1.jpg",
      "/assets/works/11/2.jpg",
    ],
  },
  {
    id: "work-12",
    preview: "/assets/works/12/preview.jpg",
    name: "Convoy  ",
    type: "Frontend Development",
    liveUrl: "https://elyor2005.github.io/Web-Clone-convoy/",
    client: "By Convoy  ",
    year: "2025",
    description:
      "I built a pixel-perfect Convoy Web Clone, replicating the landing page of the logistics and freight technology company Convoy. Developed using HTML, CSS, and JavaScript, the project focuses on recreating the clean layout, professional typography, and structured content sections of the original site. The clone is fully responsive, offering smooth navigation and layout consistency across devices. This project demonstrates my attention to detail and ability to accurately reproduce real-world UIs, making it a strong example of layout replication and front-end development best practices.",
    images: [
      "/assets/works/12/preview.jpg",
      "/assets/works/12/1.jpg",
      "/assets/works/12/2.jpg",
    ],
  },
  {
    id: "work-13",
    preview: "/assets/works/13/preview.jpg",
    name: "AdCarrot ",
    type: "Frontend Development",
    liveUrl: "https://elyor2005.github.io/Add/",
    client: "By AdCarrot ",
    year: "2025",
    description:
      "I created AdCarrot, a minimalist and modern landing page concept designed to promote a digital product or service with clarity and style. Built using HTML, CSS, and JavaScript, the site features a clean layout, bold headings, and smooth scrolling effects that guide the user through key content sections. The design emphasizes simplicity and focus, making it ideal for startups or promotional campaigns. This project showcases my ability to deliver lightweight, responsive, and visually appealing web experiences that align with strong branding principles.",
    images: [
      "/assets/works/13/preview.jpg",
      "/assets/works/13/1.jpg",
      "/assets/works/13/2.jpg",
    ],
  },
  {
    id: "work-14",
    preview: "/assets/works/14/preview.jpg",
    name: "DataSince ",
    type: "Frontend Development",
    liveUrl: "datasince.netlify.app",
    client: "By DataSince ",
    year: "2025",
    description:
      "I developed DataSince, a futuristic and tech-focused landing page for a data analytics or AI-driven startup. Built with React.js and Tailwind CSS, the site features a clean, responsive design enhanced by Framer Motion animations for smooth transitions and dynamic user interactions. The layout emphasizes modern typography, vibrant gradients, and clear visual hierarchy to highlight services, features, and brand identity. This project showcases my ability to build highly polished, interactive front-end experiences with modern tools and frameworks, ideal for tech, SaaS, and innovation-driven industries.",
    images: [
      "/assets/works/14/preview.jpg",
      "/assets/works/14/1.jpg",
      "/assets/works/14/2.jpg",
    ],
  },
  {
    id: "work-15",
    preview: "/assets/works/15/preview.jpg",
    name: "Inventory Pro SaaS",
    type: "Full-Stack Development",
    liveUrl: "https://inventory-app-mu-inky.vercel.app/",
    client: "Personal Project",
    year: "2025",
    description:
      "A high-performance Full-Stack inventory management system built with Next.js 15 and TypeScript. I engineered a robust backend architecture using Prisma ORM and PostgreSQL to handle complex data relationships, integrated with AWS S3 and Cloudinary for secure, scalable asset storage. The application features a secure multi-strategy authentication system via Better-Auth and a localized UI using Next-intl. By implementing Drag-and-Drop (dnd-kit) and Markdown support, I created a seamless user experience for managing product catalogs and warehouse workflows in a modern, dark-mode ready dashboard.",
    images: [
      "/assets/works/15/preview.jpg",
      "/assets/works/15/1.jpg",
      "/assets/works/15/2.jpg",
    ],
  },
  {
    id: "work-16",
    preview: "/assets/works/16/preview.jpg",
    name: "Firstify Business System",
    type: "Full-Stack Development",
    liveUrl: "https://firs-ti-fy.vercel.app/",
    client: "Internal Business Solution",
    year: "2025",
    description:
      "Firstify is an enterprise-grade business management system built on the cutting edge of the React ecosystem (Next.js 16 & React 19). I architected a seamless end-to-end experience featuring complex server-side logic with Prisma and PostgreSQL, paired with a highly reactive frontend utilizing TanStack Query and Zustand. The platform incorporates a refined UI/UX using Radix UI primitives and custom GSAP/Framer Motion sequences for high-end visual storytelling. Key features include secure multi-role authentication via Better-Auth, real-time data visualization with Recharts, and automated cloud storage integration through AWS S3, all wrapped in a localized, type-safe environment.",
    images: [
      "/assets/works/16/preview.jpg",
      "/assets/works/16/1.jpg",
      "/assets/works/16/2.jpg",
    ],
  },
  {
    id: "work-17",
    preview: "/assets/works/17/preview.jpg",
    name: "AeroSound Immersive Experience",
    type: "Creative Frontend Development",
    liveUrl: "https://headphones-fawn.vercel.app/",
    client: "Concept E-commerce",
    year: "2026",
    description:
      "A high-end, immersive product landing page designed to push the boundaries of web interactivity. I utilized Next.js 16 and Tailwind CSS 4 to build a hyper-performant foundation, but the core of the project lies in the sophisticated animation orchestration. By combining GSAP for complex timeline-based scroll sequences and Framer Motion for organic component interactions, I created a seamless 'cinematic' browsing experience. This project highlights my expertise in performance optimization for motion-heavy sites and my ability to translate premium brand identities into interactive digital realities.",
    images: [
      "/assets/works/17/preview.jpg",
      "/assets/works/17/1.jpg",
      "/assets/works/17/2.jpg",
    ],
  },
  {
    id: "work-18",
    preview: "/assets/works/18/preview.jpg",
    name: "Selhono Architecture & Interiors",
    type: "Creative Frontend Development",
    liveUrl: "https://selhon.vercel.app/",
    client: "Luxury Design Studio",
    year: "2026",
    description:
      "A sophisticated digital experience for an architecture and interior design studio. I leveraged Next.js 16.1 and Tailwind CSS 4 to create a high-performance foundation capable of handling large-scale high-definition imagery without compromising on speed. The project features complex GSAP-driven parallax effects and Framer Motion layout transitions that mirror the elegance of the brand’s physical spaces. By implementing modern frontend patterns, I focused on creating an immersive, 'magazine-style' browsing experience that guides users through a portfolio of luxury living and commercial design projects.",
    images: [
      "/assets/works/18/preview.jpg",
      "/assets/works/18/1.jpg",
      "/assets/works/18/2.jpg",   
    ],
  },
  {
    id: "work-19",
    preview: "/assets/works/19/preview.jpg",
    name: "Velocity Bike Systems",
    type: "Frontend Development",
    liveUrl: "https://bike-roan-ten.vercel.app/",
    client: "Personal Project",
    year: "2026",
    description:
      "A high-performance, multi-language e-commerce interface designed for a global cycling brand. Developed with Next.js 16.1 and Tailwind CSS 4, the platform features a full internationalization (i18n) system using next-intl, supporting seamless language switching and localized content delivery. I integrated Framer Motion to create fluid, physics-based interactions that reflect the dynamic nature of the product, while Lucide-react and Flag-icons ensure a clean, intuitive navigation experience. This project demonstrates my proficiency in building scalable, accessible, and globally-aware web applications.",
    images: [
      "/assets/works/19/preview.jpg",
      "/assets/works/19/1.jpg",
      "/assets/works/19/2.jpg",
    ],
  },
  {
    id: "work-20",
    preview: "/assets/works/20/preview.jpg",
    name: "Lumina Jewelry Boutique",
    type: "Frontend Development",
    liveUrl: "https://jewelry-wheat.vercel.app/",
    client: "Personal Project",
    year: "2026",
    description:
      "A luxury e-commerce storefront designed with a focus on minimalist aesthetics and high-end typography. I utilized Next.js 16 and Tailwind CSS 4 to engineer a lightning-fast browsing experience that prioritizes visual clarity and product storytelling. The interface is elevated by bespoke Framer Motion transitions, creating a 'soft-touch' digital feel that mirrors the premium nature of fine jewelry. This project highlights my ability to use whitespace, grid systems, and subtle motion to build sophisticated brand identities that resonate with a high-end clientele.",
    images: [
      "/assets/works/20/preview.jpg",
      "/assets/works/20/1.jpg",
      "/assets/works/20/2.jpg",
    ],
  },
  {
    id: "work-21",
    preview: "/assets/works/21/preview.jpg",
    name: "Nexus Agency Landing",
    type: "Frontend Development",
    liveUrl: "https://agency-one-bice.vercel.app/",
    client: "Creative Agency Concept",
    year: "2026",
    description:
      "A high-impact landing page tailored for modern creative and digital agencies. I engineered this project using Next.js 16 and Tailwind CSS 4 to ensure industry-leading performance and SEO optimization. The site features advanced GSAP scroll-triggered animations and seamless dark/light mode switching via Next-themes, allowing for a versatile user experience. By integrating a modular component architecture, I focused on creating a scalable design system that balances bold typography with high-fidelity motion graphics to establish brand authority and drive lead generation.",
    images: [
      "/assets/works/21/preview.jpg",
      "/assets/works/21/1.jpg",
      "/assets/works/21/2.jpg",
    ],
  },
  {
    id: "work-22",
    preview: "/assets/works/22/preview.jpg",
    name: "NomadQuest Travel Hub",
    type: "Frontend Development",
    liveUrl: "https://trevel-seven.vercel.app/",
    client: "Leisure & Tourism Concept",
    year: "2026",
    description:
      "A dynamic travel exploration platform designed for the modern adventurer. Built with Next.js 16 and Tailwind CSS 4, the application features an intuitive search interface with integrated price filtering via rc-slider and localized date handling with date-fns. I orchestrated a vibrant user experience using GSAP for immersive hero transitions and Framer Motion for interactive booking elements. The project emphasizes mobile-first design and high-performance asset loading, ensuring a seamless experience for users planning their next journey across any device.",
    images: [
      "/assets/works/22/preview.jpg",
      "/assets/works/22/1.jpg",
      "/assets/works/22/2.jpg",
    ],
  },
  {
    id: "work-23",
    preview: "/assets/works/23/preview.jpg",
    name: "NestLink SaaS Ecosystem",
    type: "Full-Stack Development",
    liveUrl: "https://nest-link-nine.vercel.app/",
    client: "SaaS Personal Project",
    year: "2026",
    description:
      "A comprehensive SaaS infrastructure built with Next.js 16 and React 19, designed for scalable user management and automated communication workflows. I implemented a secure authentication system using Better-Auth and engineered a transactional email pipeline using React Email and Nodemailer for professional user engagement. The backend is powered by Prisma ORM for type-safe database interactions and AWS S3 for cloud asset management. To ensure a premium user experience, I integrated TanStack Query for efficient server-state management and crafted a high-fidelity UI using Shadcn/UI, GSAP, and Framer Motion.",
    images: [
      "/assets/works/23/preview.jpg",
      "/assets/works/23/1.jpg",
      "/assets/works/23/2.jpg",
    ],
  },
];
